=== MDWASIMHAIDER/XML/Xml/AddressUsingGroupGlobalEleAttributeExample.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:group name="AccountGroup">
		<!--group creation-->
		<xs:sequence>
			<xs:element name="ac-holder-name" type="xs:string"/>
			<xs:element name="branch-name" type="xs:string"/>
			<xs:element name="ifsc" type="xs:string"/>
		</xs:sequence>
	</xs:group>
	<xs:complexType name="savingType">
		<xs:sequence>
			<xs:group ref="AccountGroup"/>
			<xs:element name="min-balance" type="xs:double"/>
		</xs:sequence>
		<xs:attribute name="firstName" type="xs:string" fixed="Md"/>
	</xs:complexType>
	<xs:complexType name="currentType">
		<xs:sequence>
			<xs:group ref="AccountGroup"/>
			<xs:element name="tx-limit">  <!--here we are defining attributes for simple element  define under element tag-->
				<xs:complexType>
					<xs:attribute name="initial-amount" type="xs:positiveInteger" use="optional"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="turnOver" type="xs:positiveInteger" use="required"/><!--this attribute define for compound element inside complextype -->
		<xs:attribute name="balanceAmount" type="xs:double" default="12.5"/>
		<!--this(use="required") make it as compulsory element -->
		<!-- here default="12.5" takes default value of attribute type-->
		<!-- attribute cretaion-->
	</xs:complexType>
	<xs:complexType name="bankType">
		<xs:sequence>
			<xs:element name="savingd-account" type="savingType"/>
			<xs:element name="currentType" type="currentType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="bank-account" type="bankType"/>
</xs:schema>

=== MDWASIMHAIDER/XML/Xml/AddressUsingGlobalEleAttribute.xml
<?xml version="1.0" encoding="UTF-8"?>
<bank-account xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/Xml/AddressUsingGroupGlobalEleAttributeExample.xsd">
	<savingd-account firstName="Md"><!--here md is rtaken as default value as Md-->
		<ac-holder-name>wasim</ac-holder-name>
		<branch-name>adampur</branch-name>
		<ifsc>bkid002</ifsc>
		<min-balance>2000</min-balance>
	</savingd-account>
	<currentType turnOver="14567" balanceAmount="132456.65"><!--here turnover attribute became madatory bebcause of xsd rule-->
		<ac-holder-name>bharat</ac-holder-name>
		<branch-name>gaziabad</branch-name>
		<ifsc>sbi1002</ifsc>
		<tx-limit>8999999</tx-limit>
	</currentType>
</bank-account>
