=== MDWASIMHAIDER/XML/Xml/AddressUsingInheritance.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="addressLineType">
		<xs:sequence>
			<xs:element name="line1" type="xs:string"/>
			<xs:element name="line2" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="usAddressType">
		<xs:complexContent>
			<xs:extension base="addressLineType">
				<xs:sequence>
					<xs:element name="zip" type="xs:int" minOccurs="1" maxOccurs="unbounded"/>
					<xs:element name="state" type="xs:string" minOccurs="0" maxOccurs="4"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ukAddressType">
		<xs:complexContent>
			<xs:extension base="addressLineType">
				<xs:sequence>
					<xs:element name="portal" type="xs:string"/>
					<xs:element name="country" type="xs:string"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="addressType">
		<xs:sequence>
			<xs:element name="us-address" type="usAddressType"/>
			<xs:element name="uk-address" type="ukAddressType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="address" type="addressType"/>
</xs:schema>

=== MDWASIMHAIDER/XML/Xml/AddressUsingInheritance.xml
<?xml version="1.0" encoding="UTF-8"?>
<address xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/Xml/AddressUsingInheritance.xsd">
	<us-address>
		<line1>main</line1>
		<line2>sustitute</line2>
		<zip>4573893</zip>
		<state>california</state>
	</us-address>
	<uk-address>
		<line1>loop</line1>
		<line2>main</line2>
		<portal>uk.com</portal>
		<country>russia</country>
	</uk-address>
</address>
