=== MDWASIMHAIDER/XML/Xml/Flight.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="id" type="xs:int"/>
<xs:element name="concession-fare" type="xs:double"/>
	<xs:complexType name="domastic-flightType">
		<xs:sequence>
			<xs:element ref="id"/><!-- global element declaration-->
			<xs:element name="email" type="xs:string"/>
			<xs:element name="source" type="xs:string"/>
			<xs:element name="destination" type="xs:string"/>
			<xs:element ref="concession-fare"/><!-- global element declaration-->
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="internationalFlightType">
		<xs:complexContent>
			<xs:extension base="domastic-flightType">
				<xs:sequence>
					<xs:element name="budget" type="xs:double"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="flightType">
		<xs:sequence>
			<xs:element name="domastic-flight" type="domastic-flightType"/>
			<xs:element name="international-flight" type="internationalFlightType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="flight" type="flightType"/>
</xs:schema>

=== MDWASIMHAIDER/XML/Xml/Flight.xml
<?xml version="1.0" encoding="UTF-8"?>
<flight xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/Xml/Flight.xsd">
	<domastic-flight>
		<id>1001</id>
		<email>wasim@gmail</email>
		<source>hyd</source>
		<destination>patna</destination>
		<concession-fare>120.78</concession-fare>
	</domastic-flight>
	<international-flight>
		<id>2001</id>
		<email>jack@gmail</email>
		<source>lossAngeles</source>
		<destination>australia</destination>
		<concession-fare>240.87</concession-fare>
		<budget>437896</budget>
	</international-flight>
</flight>
