=== MDWASIMHAIDER/XML/Xml/netCodeTest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Customer">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="Dob" type="xs:date" />
            <xs:element name="Address">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Line1" type="xs:string" />
                        <xs:element name="Line2" type="xs:string" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:element name="Supplier">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="Phone" type="xs:integer" />
            <xs:element name="Address">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Line1" type="xs:string" />
                        <xs:element name="Line2" type="xs:string" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:complexType name="businessType">
	<xs:sequence>
	<xs:element name="bill-amount" type="xs:double"/>
		<xs:element ref="Supplier"/>
		<xs:element ref="Customer"/>
	</xs:sequence>
</xs:complexType>
<xs:element name="business" type="businessType"/>
</xs:schema>

=== MDWASIMHAIDER/XML/Xml/internetCOdeTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<business xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/Xml/netCodeTest.xsd">
	<bill-amount>6546.98</bill-amount>
	<Supplier>
		<Phone>988765533</Phone>
		<Address>
			<Line1>bhg</Line1>
			<Line2>jjhhftry</Line2>
		</Address>
	</Supplier>
	<Customer>
		<Dob>1991-04-02</Dob>
		<Address>
			<Line1>oiuy</Line1>
			<Line2>ggjjkhh</Line2>
		</Address>
	</Customer>
</business>
