=== MDWASIMHAIDER/XML/Xml/po.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:complexType name="itemType">
		<xs:choice>
			<xs:element name="item-code"  type="xs:string"/>
			<xs:element name="quantity"  type="xs:string"/>
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="itemsType"><!-- xs:all ->meant for it not follow any order-->
		<xs:sequence>
			<xs:element name="item" type="itemType"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="orderType">
		<xs:sequence>
			<xs:element name="items"  type="itemsType"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="shippingType">
		<xs:sequence>
			<xs:element name="line1" type="xs:string"/>
			<xs:element name="line2" type="xs:string"/>
			<xs:element name="city"  type="xs:string"/>
			<xs:element name="state"  type="xs:string"/>
			<xs:element name="zip"  type="xs:string"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="purchaseType">
		<xs:sequence>
			<xs:element name="order-item"  type="orderType"/>
			<xs:element name="shipping-address"  type="shippingType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="purchase-order"  type="purchaseType"/>
</xs:schema>

=== MDWASIMHAIDER/XML/Xml/po.xml
<?xml version="1.0" encoding="UTF-8"?>
<purchase-order xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/Xml/po.xsd">
	<order-item>
		<items>
			<item>
				<item-code>ASD321B</item-code>
			</item>
		</items>
	</order-item>
	<shipping-address>
		<line1>Badi khanjarpur</line1>
		<line2>Near Tilkamanjhi</line2>
		<city>Bhagalpur</city>
		<state>Bihar</state>
		<zip>812001</zip>
	</shipping-address>
</purchase-order>
