=== MDWASIMHAIDER/XML/Xml/ProductionPlan.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="planType">
		<xs:sequence>
			<xs:element name="id" type="xs:int"/>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="type" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="mainPlant">
		<xs:sequence>
			<xs:element name="scap" type="planType"/>
			<xs:element name="ccap" type="planType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Main-Plant" type="mainPlant"/>
</xs:schema>

=== MDWASIMHAIDER/XML/Xml/ProductionPlan.xml
<?xml version="1.0" encoding="UTF-8"?>
<Main-Plant xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/Xml/ProductionPlan.xsd">
	<scap>
		<id>1001</id>
		<name>wasim</name>
		<type>water</type>
	</scap>
	<ccap>
		<id>2001</id>
		<name>bharat</name>
		<type>solar</type>
	</ccap>
</Main-Plant>
