=== MDWASIMHAIDER/XML/Xml/purchase.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT item-code (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT address-line1 (#PCDATA)>
<!ELEMENT address-line2 (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT zip (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT item (item-code*,quantity+)>
<!ELEMENT order-items (item)>
<!ELEMENT shipping-address (address-line1?,address-line2,city,state,zip,country)>
<!ELEMENT purchase-order (order-items,shipping-address)>
<!ATTLIST purchase-order purchase-id CDATA  #REQUIRED> 
<!ATTLIST purchase-order shop CDATA #FIXED "v-mart"> 
<!ATTLIST purchase-order dept CDATA #IMPLIED>
<!ATTLIST purchase-order purchase-type (cash|cheque) "cash">

=== MDWASIMHAIDER/XML/Xml/purchase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE purchase-order SYSTEM "D:\Xml\purchase.dtd">
<purchase-order purchase-id="101" shop="v-mart" dept="kids" purchase-type="cash">
	<order-items>
		<item>
			<item-code/>
			<item-code></item-code>
			<quantity></quantity>
		</item>
	</order-items>
	<shipping-address>
		<address-line1></address-line1>
		<address-line2/>
		<city/>
		<state/>
		<zip/>
		<country/>
	</shipping-address>
</purchase-order>
