=== MDWASIMHAIDER/XML/Xml/style2TypeWritingXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="purchase-order">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="order-item">
					<xs:complexType>
						<xs:sequence>
						<xs:element name="items">
							<xs:complexType>
							<xs:sequence>
								 <xs:element name="item-code" type="xs:string"/>
								<xs:element name="quantity" type="xs:int"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="shipping-address">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="line1" type="xs:string"/>
							<xs:element name="line2" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== MDWASIMHAIDER/XML/Xml/style2TypeWritingXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<purchase-order xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/Xml/style2TypeWritingXSD.xsd">
	<order-item>
		<items>
			<item-code>10AC234</item-code>
			<quantity>234</quantity>
		</items>
	</order-item>
	<shipping-address>
		<line1>Bhgalpur</line1>
		<line2>Bihar</line2>
	</shipping-address>
</purchase-order>
