=== MDWASIMHAIDER/XML/Xml/style1TypeWritingXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="shippingType">
		<xs:sequence>
			<xs:element name="city" type="xs:string"/>
			<xs:element name="state" type="xs:string"/>
			<xs:element name="zip" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="orderItemType">
		<xs:sequence>
			<xs:element name="item" type="itemType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="itemType">
		<xs:sequence>
			<xs:element name="item-code" type="xs:string"/>
			<xs:element name="quantity" type="xs:int"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="purchaseOrderType">
		<xs:sequence>
			<xs:element name="order-item" type="orderItemType"/>
			<xs:element name="shipping-address" type="shippingType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="purchase-order" type="purchaseOrderType"/>
</xs:schema>

=== MDWASIMHAIDER/XML/Xml/style1TypeWritingXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<purchase-order xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/Xml/style1TypeWritingXSD.xsd">
	<order-item>
		<item>
			<item-code/>
			<quantity>24</quantity>
		</item>
	</order-item>
	<shipping-address>
		<city>bhaglpur</city>
		<state>bohar</state>
		<zip>812001</zip>
	</shipping-address>
</purchase-order>
