=== MDWASIMHAIDER/XML/Xml/TravelAgency.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="passengerType">
		<xs:sequence>
			<xs:element name="passenger-name" type="xs:string"/>
			<xs:element name="passenger-email" type="xs:string"/>
			<xs:element name="journey-date" type="xs:date"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="flightType">
		<xs:sequence>
			<xs:element name="fight-num" type="xs:string"/>
			<xs:element name="pilot-name" type="xs:string"/>
			<xs:element name="pilot-contact" type="xs:positiveInteger"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="travel-agency">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="passenger" type="passengerType"/>
				<xs:element name="domestic-flight" type="flightType"/>
				<xs:element name="international-flight" type="flightType"/>
				<xs:element name="visa-status" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== MDWASIMHAIDER/XML/Xml/TraveAgency.xml
<?xml version="1.0" encoding="UTF-8"?>
<travel-agency xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/Xml/TravelAgency.xsd">
	<passenger>
		<passenger-name>wasim</passenger-name>
		<passenger-email>wasim@91</passenger-email>
		<journey-date>1991-04-02</journey-date>
	</passenger>
	<domestic-flight>
		<fight-num>luk-A1414</fight-num>
		<pilot-name>liza</pilot-name>
		<pilot-contact>98876654</pilot-contact>
	</domestic-flight>
	<international-flight>
		<fight-num>AMC15461</fight-num>
		<pilot-name>leon</pilot-name>
		<pilot-contact>987563568</pilot-contact>
	</international-flight>
	<visa-status/>
</travel-agency>
